// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpVzlHufC8krMtw6flXUHOOU0ek31Jroc',
    appId: '1:1058394040823:web:206c67fefa503ebef3a6f2',
    messagingSenderId: '1058394040823',
    projectId: 'expensetracker-8dc98',
    authDomain: 'expensetracker-8dc98.firebaseapp.com',
    storageBucket: 'expensetracker-8dc98.firebasestorage.app',
    measurementId: 'G-5PN8SM121W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCela6EIbzQslh9vgGxgy9T0le8265Lcjk',
    appId: '1:1058394040823:android:f864dcaa535d26c8f3a6f2',
    messagingSenderId: '1058394040823',
    projectId: 'expensetracker-8dc98',
    storageBucket: 'expensetracker-8dc98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzLfnLSvmvD8-vEn6YCa0m0oAqRO1zhCE',
    appId: '1:1058394040823:ios:307596cd1e8afbe8f3a6f2',
    messagingSenderId: '1058394040823',
    projectId: 'expensetracker-8dc98',
    storageBucket: 'expensetracker-8dc98.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzLfnLSvmvD8-vEn6YCa0m0oAqRO1zhCE',
    appId: '1:1058394040823:ios:307596cd1e8afbe8f3a6f2',
    messagingSenderId: '1058394040823',
    projectId: 'expensetracker-8dc98',
    storageBucket: 'expensetracker-8dc98.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpVzlHufC8krMtw6flXUHOOU0ek31Jroc',
    appId: '1:1058394040823:web:07b1f3eb714aa296f3a6f2',
    messagingSenderId: '1058394040823',
    projectId: 'expensetracker-8dc98',
    authDomain: 'expensetracker-8dc98.firebaseapp.com',
    storageBucket: 'expensetracker-8dc98.firebasestorage.app',
    measurementId: 'G-ZREF8Z4GBN',
  );
}
